config/routes.rb
Rails.application.routes.draw do
  get 'suggestions/new'

  get 'suggestions/create'

  root to: 'bicycles#index'

  devise_for :users

  namespace :users do
    resources :bicycles, only: %i(index new edit)
  end

  resources :bicycles do
    post :use, on: :member

    resources :suggestions
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, Bicycle, user_id: user.id
    can :manage, Suggestion, bicycle: { user_id: user.id }
    can [:use, :read], Bicycle
    can :create, Suggestion
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bicycle.rb
class Bicycle < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true, length: { maximum: 1000 }

  mount_uploader :image, ImageUploader

  belongs_to :category
  belongs_to :user

  has_many :suggestions

  default_scope { order(created_at: :desc) }

  def self.search(param, bicycles)
    if param
      bicycles.where('name ILIKE ? OR description ILIKE ?', "%#{param}%", "%#{param}%")
    else
      bicycles
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true

  has_many :bicycles
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  belongs_to :user
  belongs_to :bicycle
end

app/models/usage.rb
class Usage < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bicycles
  has_many :usages
  has_many :suggestions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do
    redirect_to root_path, :alert => 'Access Denied!'
  end
end

app/controllers/bicycles_controller.rb
class BicyclesController < ApplicationController
  load_and_authorize_resource

  before_action :initialize_bicycle, except: %i(index create)
  before_action :initialize_categories, only: %i(index show)

  def index
    @bicycles = Bicycle.search(params[:param], bicycles).paginate(page: params[:page], per_page: 2)
  end

  def show
  end

  def create
    @bicycle = Bicycle.create(bicycle_params)

    redirect_to users_bicycles_path
  end

  def update
    @bicycle.update_attributes(bicycle_params)

    redirect_to users_bicycles_path
  end

  def destroy
    @bicycle.destroy

    redirect_to users_bicycles_path
  end

  def use
    current_user.usages.create(bicycle_id: @bicycle.id)

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  private

  def bicycles
    bicycles = Bicycle.where.not(id: current_user&.usages&.pluck(:bicycle_id))
    return bicycles.where(category_id: params[:category_id]) if params.key?(:category_id)

    bicycles
  end

  def bicycle_params
    params.require(:bicycle).permit(
        :name,
        :description,
        :image,
        :category_id
    ).merge(
        user_id: current_user.id
    )
  end

  def initialize_bicycle
    @bicycle = Bicycle.find(params[:id])
  end

  def initialize_categories
    @categories = Category.all
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!
  before_action :set_bicycle
  before_action :set_suggestion, only: %i(edit update destroy)

  def index
    @suggestions = @bicycle.suggestions.paginate(page: params[:page], per_page: 5)
  end

  def new
    @suggestion = Suggestion.new
  end

  def create
    current_user.suggestions.create(suggestion_params)

    redirect_to @bicycle, notice: 'Suggested!'
  end

  def edit
  end

  def update
    @bicycle.update_attributes(suggestion_params.except(:bicycle))

    destroy
  end

  def destroy
    @suggestion.destroy

    redirect_to bicycle_suggestions_path(@bicycle)
  end

  private

  def set_bicycle
    @bicycle = Bicycle.find(params[:bicycle_id])
  end

  def set_suggestion
    @suggestion = Suggestion.find(params[:id])
  end

  def suggestion_params
    params.require(:suggestion).permit(
        :name,
        :description
    ).merge(
         bicycle: @bicycle
    )
  end
end

app/controllers/users/bicycles_controller.rb
module Users
  class BicyclesController < ApplicationController
    before_action :authenticate_user!
    before_action :initialize_categories, only: %i(new edit)

    def index
      @bicycles = current_user.bicycles.paginate(page: params[:page], per_page: 10)
    end

    def new
      @bicycle = Bicycle.new
    end

    def edit
      @bicycle = Bicycle.find(params[:id])
    end

    private

    def initialize_categories
      @categories = Category.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bicycles_helper.rb
module BicyclesHelper
  def can_suggest?
    !current_user&.suggestions&.exists?(bicycle_id: params[:id])
  end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/bicycles/_bicycle.haml
.wrapper{id: bicycle.id}
  .row
    .col-md-5
      %h2
        %a{href: bicycle_path(bicycle)}
          = bicycle.name
      %p.lead
        = "by #{bicycle.user.email}"
      %p
        %span.glyphicon.glyphicon-time
        = "Posted on #{bicycle.created_at.localtime.strftime("%B %d, %Y at %r")}"
    .col-md-7.text-right
      = link_to 'Use it!', use_bicycle_path(bicycle), remote: true, method: :post, class: 'btn btn-danger' if current_user.present?
  %img.img-responsive{src: bicycle.image.face.url}
  %br
  %p
    = truncate(bicycle.description.gsub(/\n/, '<br>').html_safe, length: 400)
  %a.btn.btn-primary{href: bicycle_path(bicycle)}
    Read More
  %hr

app/views/bicycles/_bicycles.haml
= render @bicycles
%br
.text-center
  = "No result" unless @bicycles.any?
  = will_paginate @bicycles, renderer: BootstrapPagination::Rails

app/views/bicycles/index.haml
.row
  .col-md-8
    %h1.page-header.text-center Bicycles
    #bicycles
      = render 'bicycles/bicycles'
  .col-md-4
    .well
      %h4.text-center Search
      = form_tag(bicycles_path, method: :get, remote: true, id: 'search-bicycles') do
        .input-group
          = text_field_tag :param, params[:param], class: 'form-control'
          = hidden_field_tag :category_id, params[:category_id] if params.key?(:category_id)
    = render 'categories/list'
    = render 'shared/widget'
%hr

app/views/bicycles/index.js.erb
$("#bicycles").html("<%= escape_javascript(render("bicycles/bicycles")) %>");

app/views/bicycles/show.haml
%hr
.row
  .col-md-8
    .row
      .col-md-5
        %h2
          = @bicycle.name
        %p.lead
          = "by #{@bicycle.user.email}"
        %p
          %span.glyphicon.glyphicon-time
          = "Posted on #{@bicycle.created_at.localtime.strftime("%B %d, %Y at %r")}"
      .col-md-7.text-right
        = link_to 'Use it!', use_bicycle_path(@bicycle), method: :post, class: 'btn btn-danger' if current_user.present?
    %hr
    %img.img-responsive{src: @bicycle.image.face.url}
    %hr
    %p
      = @bicycle.description.gsub(/\n/, '<br>').html_safe
    %br
    .text-center
      = link_to 'Suggest', new_bicycle_suggestion_path(@bicycle), class: 'btn btn-lg btn-success' if current_user && can_suggest?
  .col-md-4
    = render 'categories/list'
    = render 'shared/widget'
%hr

app/views/bicycles/use.js.erb
$(document.getElementById(<%= @bicycle.id %>)).hide(500)

app/views/categories/_category.haml
%li
  = link_to category.title, bicycles_path(category_id: category.id)

app/views/categories/_list.haml
.well
  %h4 Categories
  .row
    %ul.list-unstyled
      - @categories.each_with_index do |c, i|
        %div{class: ('col-lg-6' if i % 4)}
          = render c

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bugcycle
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'shared/navbar'
    .container
      = yield
      = render 'shared/footer'

app/views/shared/_footer.haml
%footer
  .row
    .col-lg-12
      %p.text-center
        = "Copyright © Bugcycle #{Date.today.year}"

app/views/shared/_navbar.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path} Bugcycle
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          %a{href: root_path} Home
        - if current_user
          %li
            %a{href: users_bicycles_path} Bicycles panel
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li
            %a{href: destroy_user_session_path, "data-method" => :delete } Logout
        - else
          %li
            %a{href: new_user_session_path} Login
          %li
            %a{href: new_user_registration_path} Sign-Up

app/views/shared/_widget.haml
.well
  %h4 Side Widget Well
  %p Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.

app/views/suggestions/_form.haml
.center
  = form_for [@bicycle, @suggestion] do |f|
    %p
      = f.label :name
      = f.text_field :name, value: @bicycle.name, class: 'form-control'
    %p
      = f.label :description
      = f.text_area :description, value: @bicycle.description, class: 'form-control', rows: 10
    = f.submit 'Suggest', class: 'btn btn-success'

app/views/suggestions/_suggestion.haml
.center
  %hr
  .row
    .text-right
      = link_to 'Reject', bicycle_suggestion_path(@bicycle, suggestion), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning'
    .col-md-8
      %h2
        %a{href: edit_bicycle_suggestion_path(@bicycle, suggestion)}
          = suggestion.name
      %p.lead
        = "by #{suggestion.user.email}"
      %p
        %span.glyphicon.glyphicon-time
        = "Suggested on #{suggestion.created_at.localtime.strftime("%B %d, %Y at %r")}"
  %br
  %p
    = suggestion.description.gsub(/\n/, '<br>').html_safe
  %hr

app/views/suggestions/edit.haml
%ol.breadcrumb
  %li
    = link_to 'Bicycles', users_bicycles_path
  %li
    = link_to 'Suggesions', bicycle_suggestions_path(@bicycle)
  %li.active Merge

.center
  = form_for [@bicycle, @suggestion] do |f|
    %p
      = f.label :name
      = f.text_field :name, class: 'form-control'
    %p
      = f.label :description
      = f.text_area :description, class: 'form-control', rows: 10
    = f.submit 'Approve', class: 'btn btn-success'

app/views/suggestions/index.haml
%ol.breadcrumb
  %li
    = link_to 'Bicycles', users_bicycles_path
  %li.active Suggestions

= render @suggestions
%br
.text-center
  = "No result" unless @suggestions.any?
  = will_paginate @suggestions, renderer: BootstrapPagination::Rails

app/views/suggestions/new.haml
%ol.breadcrumb
  %li
    = link_to @bicycle.name.capitalize, @bicycle
  %li.active Suggest

= render 'suggestions/form'

app/views/users/bicycles/_bicycle.haml
%tr.info
  %td.text-center
    = link_to " #{bicycle.name}", bicycle_path(bicycle), class: 'glyphicon-th-list'
  %td.text-center
    = bicycle.category.title
  %td.text-center
    = bicycle.created_at.localtime.strftime("%d/%m/%Y at %r")
  %td.text-center
    = link_to bicycle.suggestions.size, bicycle_suggestions_path(bicycle)
  %td.text-center
    = link_to 'Edit', edit_users_bicycle_path(bicycle), class: 'btn btn-primary'
  %td.text-center
    = link_to 'Delete', bicycle, method: :delete, data: {confirm: 'You sure?'}, class: 'btn btn-danger'

app/views/users/bicycles/_form.haml
= form_for @bicycle do |f|
  = image_tag @bicycle.image.preview.url if @bicycle.image.present?
  %p
    = f.label :image, 'Face'
    = f.file_field :image, class: 'form-control'
  %p
    = f.label :name
    = f.text_field :name, class: 'form-control'
  %p
    = f.label :category_id
    %br
    = f.select :category_id, @categories.collect { |c| [ c.title, c.id ] }
  %p
    = f.label :description
    = f.text_area :description, class: 'form-control', rows: 10
  = f.submit 'Save', class: 'btn btn-success'

app/views/users/bicycles/edit.haml
%ol.breadcrumb
  %li
    = link_to 'Bicycles', users_bicycles_path
  %li.active Edit

.center
  = render 'users/bicycles/form'

app/views/users/bicycles/index.haml
%h1 My Bicycles
= link_to 'Create', new_users_bicycle_path, class: 'btn btn-success'
%br

.center
  = will_paginate @bicycles, renderer: BootstrapPagination::Rails
%br
.table-responsive
  %table.table.table-bordered.table-hover
    %tr.active
      %th
        %h4 Name
      %th
        %h4.text-center Category
      %th
        %h4.text-center Date
      %th
        %h4.text-center Suggestions
      %th{colspan: 2}
        %h4.text-center Actions
    = render @bicycles

app/views/users/bicycles/new.haml
%ol.breadcrumb
  %li
    = link_to 'Bicycles', users_bicycles_path
  %li.active Add

.center
  = render 'users/bicycles/form'